# Generated by Django 5.2.17 on 2026-09-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailverify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverify',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
