# Generated by Django 5.2.17 on 2026-09-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_emailverify_is_verified_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverifyotp',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.DeleteModel(
            name='EmailVerify',
        ),
        migrations.DeleteModel(
            name='EmailVerifyOTP',
        ),
    ]
